### ISSUE TITLE
Change Magnas -> Magnus (マグナス)

### ISSUE THREAD

**Issue by choogiesaur** [Arks-Layer/PSNovaTranslations#392]
Magnas is a mistranslation IMO. There is precedent for マグナス being translated to Magnus in other games, for instance:

Ogre Battle 64: Magnus Gallant (**マグナス**・ガラント)
Tales of Destiny: Leon Magnus (リオン・**マグナス**)

as well as Magnus once being a commonly used Latin name meaning "Great".

Agreed?

**Comment by SynthSy** [comment]
Pretty sure it was a typo on our end, but we'll get this fixed in the next build.
