### ISSUE TITLE
LINK in page to download patch to Nova dont work.

### ISSUE THREAD

**Issue by Nyarlxxx** [Arks-Layer/PSNovaTranslations#404]
Hello.
LINK in page to download patch to Nova dont work.

**Comment by SynthSy** [comment]
Oh, thanks.

Current link is: https://mega.nz/#!jVY3AICC!luXnVmkUq0t_-4-AOSahtipb-7sP06c-ufaB7V0O1pc until we fix it on our website.

**Comment by Aida-Enna** [comment]
Ah, probably my fault. I cleaned out the MEGA folder today.

**Comment by Aida-Enna** [comment]
Fixed, thanks for reporting!
