### ISSUE TITLE
Build from source 

### ISSUE THREAD

**Issue by phillipnasher** [Arks-Layer/PSNovaTranslations#422]
Can somebody post a working discord link so I can figure out how to build the translation from source. The discord link I found had expired.

Thanks

**Comment by SynthSy** [comment]
https://discord.gg/pso2

**Comment by Aida-Enna** [comment]
Releases are available on the website (http://arks-layer.com/nova.php) and debug builds can be built through the discord. Be aware that these debug builds will use the source on this report, not someone elses's fork.
